Endava/BEEQ

.github/workflows/test.yml
README.md
jest.config.ts
nx.json
packages/bee-q-react/README.md
packages/bee-q/project.json

Update how to run the project locally and add clarification about the icon SVG files for Bee-Q react package.

chore: project `Doc` updates and `CI` improvements

---

packages/bee-q/src/components/badge/bq-badge.tsx
packages/bee-q/src/components/button/scss/bq-button.scss
packages/bee-q/src/components/button/scss/bq-button.variables.scss
packages/bee-q/src/components/checkbox/bq-checkbox.tsx
packages/bee-q/src/components/checkbox/scss/bq-checkbox.scss
packages/bee-q/src/components/divider/scss/bq-divider.variables.scss
packages/bee-q/src/components/notification/bq-notification.tsx
packages/bee-q/src/components/notification/scss/bq-notification.scss
packages/bee-q/src/components/notification/scss/bq-notification.variables.scss
packages/bee-q/src/components/radio/scss/bq-radio.scss
packages/bee-q/src/components/slider/__test__/bq-slider.e2e.ts
packages/bee-q/src/components/slider/bq-slider.tsx
packages/bee-q/src/components/spinner/scss/bq-spinner.scss
packages/bee-q/src/components/status/bq-status.tsx
packages/bee-q/src/components/switch/bq-switch.tsx
packages/bee-q/src/components/switch/scss/bq-switch-variables.scss
packages/bee-q/src/components/tab-group/bq-tab-group.tsx
packages/bee-q/src/components/tab/__tests__/bq-tab.e2e.ts
packages/bee-q/src/components/tab/_storybook/bq-tab.stories.tsx
packages/bee-q/src/components/tab/bq-tab.tsx
packages/bee-q/src/components/tab/readme.md
packages/bee-q/src/components/tab/scss/bq-tab-variables.scss
packages/bee-q/src/components/tab/scss/bq-tab.scss
packages/bee-q/src/components/tooltip/bq-tooltip.tsx
packages/bee-q/src/components/tooltip/scss/bq-tooltip.variables.scss
packages/bee-q/src/global/styles/themes/default/_spacing.scss
packages/bee-q/src/global/styles/themes/default/index.scss
tailwind.config.ts

The following spacing custom properties were added and all the components have been updated to use them in terms of margins/paddings spaces
```css
:root {
--bq-spacing-xs3: 2px;
--bq-spacing-xs2: 4px;
--bq-spacing-xs: 8px;
--bq-spacing-s: 12px;
--bq-spacing-m: 16px;
--bq-spacing-l: 24px;
--bq-spacing-xl: 32px;
--bq-spacing-xxl: 40px;
--bq-spacing-xxl2: 56px;
--bq-spacing-xxl3: 64px;
--bq-spacing-xxl4: 72px;
}
```

feat(Tokens): add spacing tokens

---

packages/bee-q/src/global/styles/themes/default/_text-colors.scss

This PR updates feedback text colours to match latest figma updates.

fix(tokens): make feedback text color tokens accessible

---

packages/bee-q/src/global/styles/tailwind.pcss

Following this article here: https://www.joshwcomeau.com/css/custom-css-reset/

feat(CSS reset): improve custom CSS reset

---

packages/bee-q-icons/src/executors/generate-icons/helpers/create.ts
packages/bee-q-icons/src/executors/generate-icons/helpers/download.ts
packages/bee-q-icons/src/executors/generate-icons/helpers/extract.ts
packages/bee-q/src/components/icon/helper/request.ts
packages/bee-q/src/components/notification/_storybook/bq-notification.stories.tsx
packages/bee-q/src/components/switch/__tests__/bq-switch.e2e.ts
packages/bee-q/src/shared/utils/getNextElement.ts

This fixes the major issues spotted by SonarLint here:
https://sonarcloud.io/project/issues?resolved=false&severities=MAJOR&id=Endava_bee-q

fix(Sonarlint): resolve major issues spotted by Sonarcloud

---

packages/bee-q/src/components/dialog/bq-dialog.tsx
packages/bee-q/src/components/dialog/scss/bq-dialog.scss
packages/bee-q/src/components/dialog/scss/bq-dialog.variables.scss

https://github.com/Endava/bee-q/assets/328492/1dc70f6d-96d8-446e-a949-0cd48742d536

fix(dialog): footer padding when standard and highlight

---

.github/renovate.json5
package-lock.json
package.json
packages/bee-q/src/global/styles/mixins/_keyframes.scss
packages/bee-q/src/shared/test-utils/__tests__/computedStyle.spec.ts
packages/bee-q/src/shared/test-utils/computedStyle.ts

This reverts commit [bd521fbb2705ad785abdee317c56f9a554fe114c](https://github.com/Endava/bee-q/commit/bd521fbb2705ad785abdee317c56f9a554fe114c).

revert(deps): update dependency prettier to v3

---

packages/bee-q/src/components/icon/helper/request.ts

Also, remove an unnecessary accesrtion since it does not change the type of the expression.

style(icon): expected non-Promise value in a boolean conditional

---

packages/bee-q/src/components/tab/__tests__/bq-tab.e2e.ts
packages/bee-q/src/components/tab/bq-tab.tsx
packages/bee-q/src/components/tab/scss/bq-tab-variables.scss
packages/bee-q/src/components/tab/scss/bq-tab.scss

Add more and document CSS variables

fix(tab): wrong gap space between icon and label

---

packages/bee-q/src/components/input/bq-input.tsx

Avoid focus and blur events to be emitted while disabled.

fix(input): clear button showing up when disabled

---

.circleci/config.yml
.github/renovate.json5

Details: https://circleci.com/docs/parallelism-faster-jobs/

ci(CircleCI): use parallelism for faster tests

---

sonar-project.properties

Ignore utils unit tests and tailwind config files.

chore(Sonarcloud): update code duplications exclusion pattern

---

packages/bee-q/src/services/libraries/floating-ui/index.ts
sonar-project.properties

This solves the following Sonarcloud issue:
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=Endava_bee-q&open=AYnjsUslhVwgu7aqVZdL

fix(FloatingUI): use object spread instead of `Object.assign()`

---

packages/beeq/src/components/tooltip/scss/bq-tooltip.scss
packages/beeq/src/components/tooltip/scss/bq-tooltip.variables.scss

fix(Tooltip): add z-index to the tooltip panel

---

package-lock.json
packages/beeq/src/components/badge/__tests__/bq-badge.e2e.ts
packages/beeq/src/components/badge/scss/bq-badge.variables.scss

Badge borders have been removed in Figma:

fix(Badge): remove border styles

---

.github/workflows/deploy.yml

Let's try publishing the Storybook playground to Github Pages 😉

chore(CI): add a Github pages deploy workflow

---

chromatic.config.json
package-lock.json
package.json
packages/beeq/.storybook/main.ts

Details: https://www.chromatic.com/docs/visual-tests-addon/

docs(Storybook): enable visual tests addon

---

packages/beeq/src/components.d.ts
packages/beeq/src/components/dialog/bq-dialog.tsx
packages/beeq/src/components/dropdown/bq-dropdown.tsx
packages/beeq/src/components/notification/_storybook/bq-notification.stories.tsx
packages/beeq/src/components/notification/bq-notification.tsx
packages/beeq/src/components/notification/readme.md
packages/beeq/src/components/notification/scss/bq-notification.scss
packages/beeq/src/components/panel/bq-panel.tsx
packages/beeq/src/components/select/bq-select.tsx

This PR improves the open/close animation of the notification component.
_(left: current version, right: new changes)_
https://github.com/Endava/BEEQ/assets/328492/3148e12c-69a2-4c1f-a57a-1c7c4876b682
It also sets the `open` property as mutable for the Select, Dialog, Dropdown panel.

fix(Notification): improve open/close animations

---

packages/beeq/src/components/slider/bq-slider.tsx
packages/beeq/src/components/slider/scss/bq-slider.scss

fix(Slider): add `not-allowed` cursor class for disabled state

---

packages/beeq/src/components/progress/bq-progress.tsx
packages/beeq/src/components/slider/bq-slider.tsx
packages/beeq/src/components/tooltip/bq-tooltip.tsx
packages/beeq/src/components/tooltip/scss/bq-tooltip.scss

fix(Side Menu): menu items tooltip not showing correctly when collapsed

---

packages/beeq/src/components/slider/bq-slider.tsx

This PR fixes the issue where lower value is updated to max value.
Fixes #1030
https://github.com/Endava/BEEQ/assets/109202804/2f6160b4-8718-49a7-b7af-b963710c2aaa

fix(Slider): lower value updated to max value

---

packages/beeq/src/components.d.ts
packages/beeq/src/components/checkbox/bq-checkbox.tsx

https://github.com/Endava/BEEQ/issues/1035

fix(Checkbox): bq-checkbox indeterminate property is wrongly typed

---

packages/beeq/src/components/button/scss/bq-button.scss

Implements button secondary ghost styling.

feat(button): add secondary button ghost variant

---

packages/beeq/package.json
packages/beeq/src/index.ts

This PR defines the ESM/CJS exports on `@beeq/core` package.json and improves the types exports from `components.d.ts`
N/A

chore(Beeq): improve ESM exports and types export

---

packages/beeq-angular/package.json
packages/beeq-react/package.json
packages/beeq-tailwindcss/package.json
packages/beeq-vue/package.json
packages/beeq/README.md
packages/beeq/package.json

This PR revert partially the changes we have made on the `package/beeq/packages.json` in #1059.
The previous changes break how vite resolve paths from `@beeq/core/dist/*`.
Fixes #1069

fix(Beeq Core): vite fails to resolve `@beeq/core/dist/*` paths

---

package-lock.json
package.json
packages/beeq-angular/package.json
packages/beeq-react/package.json
packages/beeq-vue/package.json
packages/beeq/.eslintrc.json
packages/beeq/package.json

Update the [cally](https://github.com/WickyNilliams/cally) dependency to the latest version
Fixes N/A

chore(deps): update cally to v0.6.1

---

.sonarcloud.properties
packages/beeq-tailwindcss/src/index.ts
packages/beeq-tailwindcss/src/plugins/color-mix.ts
packages/beeq-tailwindcss/src/plugins/index.ts
packages/beeq-tailwindcss/src/plugins/logical-properties.ts
sonar-project.properties

This PR adds the utilities for the missing CSS logical properties still not supported by Tailwind CSS.

chore(Tailwind CSS): add support for missing CSS logical properties

---

packages/beeq/src/components/button/scss/bq-button.scss

refactor(Button): use CSS logical properties instead of physical values

---

packages/beeq/src/components/avatar/bq-avatar.tsx
packages/beeq/src/components/avatar/scss/bq-avatar.scss

refactor(Avatar): use CSS logical properties instead of physical values

---

packages/beeq/src/components/badge/bq-badge.tsx
packages/beeq/src/components/badge/scss/bq-badge.scss

refactor(Badge): use CSS logical properties instead of physical values

---

packages/beeq/src/components/card/_storybook/bq-card.stories.tsx
packages/beeq/src/components/card/bq-card.tsx

refactor(Card): use CSS logical properties instead of physical values

---

packages/beeq/src/components/breadcrumb-item/scss/bq-breadcrumb-item.scss
packages/beeq/src/components/breadcrumb/bq-breadcrumb.tsx

refactor(Breadcrumb): use CSS logical properties instead of physical values

---

packages/beeq/src/components/drawer/_storybook/bq-drawer.stories.tsx
packages/beeq/src/components/drawer/bq-drawer.tsx
packages/beeq/src/components/drawer/readme.md
packages/beeq/src/components/drawer/scss/bq-drawer.scss

refactor(Drawer): use CSS logical properties instead of physical values

---

packages/beeq/src/components.d.ts
packages/beeq/src/components/checkbox/_storybook/bq-checkbox.stories.tsx
packages/beeq/src/components/checkbox/bq-checkbox.tsx
packages/beeq/src/components/checkbox/readme.md
packages/beeq/src/components/checkbox/scss/bq-checkbox.scss

refactor(Checkbox): use CSS logical properties instead of physical values

---

packages/beeq/src/components/empty-state/bq-empty-state.tsx

refactor(Empty State): use CSS logical properties instead of physical values

---

packages/beeq/src/components/tag/scss/bq-tag.scss

refactor(Tag): use CSS logical properties instead of physical values

---

packages/beeq/src/components/toast/_storybook/bq-toast.stories.tsx
packages/beeq/src/components/toast/scss/bq-toast.scss

refactor(Toast): use CSS logical properties instead of physical values

---

packages/beeq/src/components/tooltip/scss/bq-tooltip.scss

refactor(Tooltip): use CSS logical properties instead of physical values

---

packages/beeq/src/components/status/bq-status.tsx
packages/beeq/src/components/status/scss/bq-status.scss

refactor(Status): use CSS logical properties instead of physical values

---

packages/beeq/src/components/spinner/bq-spinner.tsx
packages/beeq/src/components/spinner/scss/bq-spinner.scss

refactor(Spinner): use CSS logical properties instead of physical values

---

packages/beeq/src/components/textarea/_storybook/bq-textarea.stories.tsx
packages/beeq/src/components/textarea/scss/bq-textarea.scss

refactor(Textarea): use CSS logical properties instead of physical values

---

packages/beeq/src/components/progress/_storybook/bq-progress.stories.tsx
packages/beeq/src/components/progress/bq-progress.tsx
packages/beeq/src/components/progress/scss/bq-progress.scss

refactor(Progress): use CSS logical properties instead of physical values

---

packages/beeq/src/components/radio-group/scss/bq-radio-group.scss
packages/beeq/src/components/radio/scss/bq-radio.scss

refactor(Radio Group): use CSS logical properties instead of physical values

---

packages/beeq/src/components/option-group/bq-option-group.tsx
packages/beeq/src/components/option-group/scss/bq-option-group.scss
packages/beeq/src/components/option/scss/bq-option.scss

refactor(Option): use CSS logical properties instead of physical values

---

packages/beeq/src/components/side-menu/bq-side-menu.tsx
packages/beeq/src/components/side-menu/scss/bq-side-menu.scss
packages/beeq/src/global/styles/utils/_utility.scss

This PR refactors the CSS of the Side menu component, replacing CSS physical values with logical properties, to support RTL content layout.
https://github.com/user-attachments/assets/c6fc2328-f44e-464a-b8f4-5394f4c6c582

refactor(Side menu): use CSS logical properties instead of physical values

---

.gitignore
nx.json
packages/beeq/.storybook/assets/css/preview.css
packages/beeq/.storybook/preview.ts
packages/beeq/project.json
packages/beeq/src/_storybook/changelog.mdx

This PR adds a new page: `What's new` to the Storybook, showing the library changelog.

docs(Storybook): add Changelog page

---

.github/renovate.json5
package.json
packages/beeq/stencil.config.ts
pnpm-lock.yaml

chore(deps): update `@stencil/sass` to v3.1.9 and silence deprecation warnings

---

packages/beeq/src/components/dialog/scss/bq-dialog.scss
patches/@nxext__stencil@20.0.6.patch
pnpm-lock.yaml

The dialog component can get rendered off the screen when used in large pages (e.g., when the page has a scroll).
Changing the positioning from absolute to fixed solves the problems.
Fixes #1451 
https://github.com/user-attachments/assets/aaec60b7-51c8-446b-a935-197862057c31

fix(Dialog): change positioning from `absolute` to `fixed`

---

packages/beeq/src/components/icon/bq-icon.tsx
packages/beeq/src/components/icon/helper/request.ts

This PR improves the internal request helper of the BqIcon component, providing better caching and security validation.
N/A

refactor(Icon): improve SVG fetching and processing with caching and security validation
