- packages/bee-q/src/components/icon/bq-icon.tsx
This fixes an issue where the SVG icon used inside the `bq-icon` is not centered within its container when a custom size value is used.
> fix(Icon): base container alignment on custom size value

- packages/bee-q/src/components/slider/scss/bq-slider.scss
This fixes the issue where the `bq-slider` styles break when the parent container applies a display or text alignment CSS rule.
> fix(Slider): layout styles break if parent have alignment

- packages/bee-q/src/components/checkbox/bq-checkbox.tsx
This fixes the issue where the checkbox label gets separated from the checkbox square when the parent has a different text alignment.
> fix(Checkbox):  label miss-alignment if parent has different alignment

- .vscode/extensions.json
- .vscode/settings.json
This [CSS Variable Autocomplete](https://marketplace.visualstudio.com/items?itemName=vunguyentuan.vscode-css-variables) will replace the use of the [CSS Var Complete](https://marketplace.visualstudio.com/items?itemName=phoenisx.cssvar) extension.
> chore(VSCode): use `CSS Variable Autocomplete` extension

- packages/bee-q-angular/src/bee-q.module.ts
It should fix the following issue:
We tell Angular that the provider is a multi-provider.
> fix(angular wrapper): cannot mix multi and regular providers

- packages/bee-q/src/components/notification/_storybook/bq-notification.stories.tsx
- packages/bee-q/src/shared/test-utils/computedStyle.ts
- packages/bee-q/src/shared/utils/getRandom.ts
- sonar-project.properties
It fixes all the remaining Sonarcloud issues:
> fix(sonarlint): code smells and security reviews

- packages/bee-q/src/components.d.ts
- packages/bee-q/src/components/avatar/__tests__/bq-avatar.e2e.ts
- packages/bee-q/src/components/avatar/_storybook/bq-avatar.stories.tsx
- packages/bee-q/src/components/avatar/bq-avatar.tsx
- packages/bee-q/src/components/avatar/readme.md
- packages/bee-q/src/components/avatar/scss/bq-avatar.scss
- packages/bee-q/src/components/avatar/scss/bq-avatar.variables.scss
- packages/bee-q/src/components/badge/bq-badge.tsx
- packages/bee-q/src/components/badge/readme.md
- add badge
- add stroke
- trim text based on size
> feature(avatar): add badge

- packages/bee-q/src/components/input/_storybook/bq-input.stories.tsx
- packages/bee-q/src/components/input/bq-input.tsx
Fallback to `id="input"` if no `name` value has been provided.
> fix(input): native input `id` from `name` prop value

- packages/bee-q/src/components/input/bq-input.tsx
- packages/bee-q/src/components/input/scss/bq-input.scss
- tailwind.config.ts
- We made the focus inherit from Tailwind config focus,  just need to set different values for `--bq-ring-width`, `--bq-ring-offset-width`, and `--bq-ring-color-focus`.
- Make sure to emit `bqInput` on clear action too.
> fix(input): focus style missing on consumer apps

- packages/bee-q/src/components/tab-group/__tests__/bq-tab-group.e2e.ts
- packages/bee-q/src/components/tab-group/bq-tab-group.tsx
https://github.com/Endava/bee-q/assets/109202804/3b3254ff-e382-481b-acca-f25dd5f8e7b8
> fix(tab): update active tab when value is changed externally

- packages/bee-q/src/_storybook/foundation/typography.mdx
- packages/bee-q/src/components/avatar/bq-avatar.tsx
When rendering an image Avatar (no initials text has been provided), we get the following error in the browser console:
This PR will also improve the following:
- Use CSS logical properties for badge position, this will make the avatar + badge work as expected in the RTL content direction.
- Refactor `getIndex()` method to use object mapping instead of a Switch statement.
> fix(Avatar): trim initials text only if exist

- packages/bee-q/src/components/side-menu-item/__tests__/bq-side-menu-item.e2e.ts
- packages/bee-q/src/components/side-menu-item/bq-side-menu-item.tsx
- packages/bee-q/src/components/side-menu-item/scss/bq-side-menu-item.scss
- packages/bee-q/src/components/tooltip/bq-tooltip.tsx
It fixes the following issue when the side menu is collapsed
> fix(side menu item): misalignment when menu is collapsed

- package-lock.json
- package.json
- packages/beeq/.storybook/main.ts
- packages/beeq/.storybook/preview.ts
Original `whitespace-se/storybook-addon-html` do not support Prettier v3. The new add-on also uses a new theme for the HTML code preview in Storybook:
> refactor(Storybook): use forked storybook-addon-html

- package-lock.json
- package.json
- packages/beeq/.storybook/main.ts
- tailwind.config.ts
Please, notice that we're only updating the Angular version used to create the wrapper.
Beeq Angular wrapper will still work in Angular apps 14, 15, and 16 (I've tested all of them 🙂 )
> chore(deps): update Angular to v16 (major)

- .github/renovate.json5
- package-lock.json
- package.json
The `@stencil/core` v4.7.0 supports now Jest 29 🥳
> chore(deps): update Stencil to v4.7.0

- packages/beeq/src/components/input/_storybook/bq-search.input.stories.tsx
- packages/beeq/src/components/input/_storybook/bq-search.mdx
The purpose of this PR is to update the Storybook to show the use of Search based on `bq-input` component.
> docs(Search): add storybook examples for Search input

- package-lock.json
- packages/beeq/package.json
- packages/beeq/src/components.d.ts
- packages/beeq/src/components/dialog/bq-dialog.tsx
- packages/beeq/src/components/dialog/readme.md
- packages/beeq/src/components/dialog/scss/bq-dialog.scss
- packages/beeq/src/shared/utils/props.ts
This PR fixes a typo in the `footerAppearance` property name and improves the enter/leave animations when the dialog gets open/closed.
https://github.com/Endava/BEEQ/assets/328492/e9007b2b-3f16-463c-8df0-8c19c148b65c
> fix(Dialog): prop `footerAppearance` typo and open/close animations improvement

- packages/beeq/src/components.d.ts
- packages/beeq/src/components/alert/__tests__/bq-alert.e2e.ts
- packages/beeq/src/components/alert/bq-alert.tsx
- packages/beeq/src/components/alert/scss/bq-alert.scss
The purpose of this PR is to improve the open/close animation for Alert component.
> fix(Alert): improve open/close animation

- packages/beeq/src/components/accordion/scss/bq-accordion.scss
The purpose of this PR is to correct the cursor style for the off state of the accordion. The pointer-events: none rule has been moved down one level to avoid overriding this cursor: not-allowed.
> fix(Accordion): fix cursor styling in accordion for disabled state

- packages/beeq/src/components/dropdown/bq-dropdown.tsx
The purpose of this PR is to address the issue related to the disabled state management in the dropdown component. Previously, the disabled state of the dropdown was not properly synchronized with the associated button's disabled state. This PR fixes that issue by implementing a mechanism to correctly update the button's disabled state based on the dropdown's disabled property. As a result, the dropdown component now ensures consistent behavior when managing its disabled state, enhancing overall accessibility and user experience.
Before|After
-|-
> fix(Dropdown): disable the trigger element if the dropdown have `disable="true"`

- .github/CODEOWNERS
- tailwind.config.ts
The default Tailwind CSS behavior adds a lot of useless empty custom CSS properties.
with these changes, we avoid Tailwind bloating the CSS with all these custom CSS properties.
Here we're also disabling the usage of rgb/opacity, which also removes a massive block of empty Custom Properties that Tailwind generates.
N/A
https://piccalil.li/blog/a-css-project-boilerplate/
https://v2.tailwindcss.com/docs/configuration#variant-order
> perf(CSS):  remove the massive wall of empty CSS properties added by Tailwind CSS

- package-lock.json
- packages/beeq/package.json
- packages/beeq/src/components/alert/bq-alert.tsx
- packages/beeq/src/components/dialog/bq-dialog.tsx
- packages/beeq/src/components/dialog/scss/bq-dialog.scss
- packages/beeq/src/components/notification/bq-notification.tsx
- packages/beeq/src/components/notification/scss/bq-notification.scss
- packages/beeq/src/shared/utils/index.ts
- packages/beeq/src/shared/utils/transition.ts
- tailwind.config.ts
After setting `optimizeUniversalDefaults` on the Tailwind config, some transform values get overriden. This affect the Dialog position when the component is entering or leaving while transitioning.
The bug can be reproduced also in Storybook: https://storybook.beeq.design/?path=/story/components-dialog--default
N/A
I have extracted the code from the `el-transition` dependency package and moved to the project as: `packages/beeq/src/shared/utils/transition.ts`, added the types and JSDoc, that way we have complete control in case that we need to change something.
https://github.com/Endava/BEEQ/assets/328492/fe401a3e-ee36-4a95-ba20-664e02c4c038
> fix(Dialog): wrong position on entry/leave transition

- packages/beeq/src/components.d.ts
- packages/beeq/src/components/accordion-group/bq-accordion-group.tsx
- packages/beeq/src/components/accordion/__tests__/bq-accordion.e2e.ts
- packages/beeq/src/components/accordion/_storybook/bq-accordion.stories.tsx
- packages/beeq/src/components/accordion/bq-accordion.tsx
- packages/beeq/src/components/accordion/helper/index.ts
- packages/beeq/src/components/accordion/readme.md
- packages/beeq/src/components/accordion/scss/bq-accordion.scss
This PR improves the animation of the Accordion when it opens and closes. It also handles the `bqOpen` and `bqClose` events handler callback and `bqAfterOpen` | `bqAfterClose`.
Fixes #919 
https://github.com/Endava/BEEQ/assets/328492/c0c4623a-1a93-4ecc-8ca9-769bc7dddd76
Storybook preview: https://6408a8161bf55e5999ae828b-ejgiolewwn.chromatic.com/?path=/story/components-accordion--group
> fix(Accordion): improve open/close animations and handle `bqAfterOpen` and `bqAfterClose` events

- packages/beeq/src/components/icon/bq-icon.tsx
- packages/beeq/src/index.ts
- packages/beeq/src/shared/utils/assetsPath.ts
- packages/beeq/src/shared/utils/index.ts
- tools/src/executors/icons/helpers/extract.ts
This PR flattens the SVG files once extracted and copied into the `./src/components/icon/svg` folder, making it easy to get the path to the files. Now for weighted icons (e.g. bold, fill, duotone, thing) instead of having `./svg/bold/icon-name-bold.svg` we will have `./svg/icon-name-bold.svg`.
Also, we are replacing `getAssetPath()` from `@stencil/core`, which breaks on Vue projects, with a custom set/get base path method.
N/A
> refactor(Icon): flatten icon SVG files when extracted and improve assets path

- packages/beeq/src/components/progress/__tests__/bq-progress.e2e.ts
- packages/beeq/src/components/progress/_storybook/bq-progress.stories.tsx
- packages/beeq/src/components/progress/bq-progress.tsx
- packages/beeq/src/components/progress/readme.md
- packages/beeq/src/components/progress/scss/bq-progress.scss
- packages/beeq/src/components/progress/scss/bq-progress.variables.scss
- packages/beeq/src/global/styles/mixins/_keyframes.scss
The purpose of this PR is to add the style and animation for indeterminate status for progress bar.
The is a Figma design here: https://www.figma.com/file/2VS47PTSkQWJkr7H6DpAdR/BEEQ-Design-System-(v1.0)?node-id=3991%3A54962&mode=dev
https://github.com/Endava/BEEQ/assets/98550729/37d4496a-8edb-486a-9bcf-0f0b8c1438b7
> feat(Progress): add style and animation for indeterminate status

- packages/beeq/src/components/dialog/bq-dialog.tsx
Avoid the dialog to close when pressing the Esc key down if `disable-close-esc-keydown` is enabled.
Fixes #978 
https://github.com/Endava/BEEQ/assets/328492/82069cbb-3535-4a6d-a701-9d1fa68b1a49
> fix(Dialog): dialog closes on Esc down if `disable-close-esc-keydown` is enabled

- .commitlintrc.ts
- .github/renovate.json5
- packages/beeq/project.json
Renovate should group all NPM dependencies in a single PR, except those packages that matter most like `@angular/*`, `@stencil/*`, `@storybook/*`, etc.
N/A
> chore(Renovate): configure renovate to group all NPM dependencies

- packages/beeq/src/components/slider/__tests__/bq-slider.e2e.ts
- packages/beeq/src/components/slider/_storybook/bq-slider.stories.tsx
- packages/beeq/src/components/slider/bq-slider.tsx
After the latest refactoring on the Slider component, the range type is not rendering correctly when the max value is set to a value greater than 10.
N/A
The issue can be reproduced here in the latest Chromatic published from the `main` branch:
https://6408a8161bf55e5999ae828b-xajapvwgrr.chromatic.com/?path=/story/components-slider--range
> fix(Slider): range type not rendering correctly when max value is greater than 10

- packages/beeq/src/components.d.ts
- packages/beeq/src/components/slider/__tests__/bq-slider.e2e.ts
- packages/beeq/src/components/slider/_storybook/bq-slider.stories.tsx
- packages/beeq/src/components/slider/bq-slider.tsx
- packages/beeq/src/components/slider/readme.md
- packages/beeq/src/components/tooltip/bq-tooltip.tsx
- packages/beeq/src/components/tooltip/readme.md
The purpose of this PR is to enable the tooltip for slider (single and range).
> feat(Slider): allow to enable/show a Tooltip over the Slider thumb(s)

- .stylelintrc.json
- packages/beeq-tailwindcss/src/theme/colors/declarative.ts
- packages/beeq-tailwindcss/src/theme/default/dark.ts
- packages/beeq-tailwindcss/src/theme/default/light.ts
- packages/beeq-tailwindcss/src/theme/endava/dark.ts
- packages/beeq-tailwindcss/src/theme/endava/light.ts
- packages/beeq/src/components/side-menu-item/scss/bq-side-menu-item.variables.scss
- packages/beeq/src/components/side-menu/scss/bq-side-menu.scss
- packages/beeq/src/components/side-menu/scss/bq-side-menu.variables.scss
The side menu background has been changed in Figma. The default variant should now use the `ui--primary` token color. This PR also adds a border style to delimitate the Side Menu with the rest of the page.
N/A
https://www.figma.com/file/2VS47PTSkQWJkr7H6DpAdR/BEEQ-Design-System-(v1.0)?type=design&node-id=3991%3A117554&mode=design&t=EQ2925S5dDYCvMpZ-1
> refactor(Side menu): set background color to UI primary for the default variant

- packages/beeq/src/components/select/bq-select.tsx
This PR fixes an issue on the BqSelect component where the initial value defined is not displayed/reflected in the select input. 
[Code Reproduction URL](https://codesandbox.io/p/sandbox/beeq-select-xhf5c4?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clv56p48300063p6fm33e1hdy%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%2 …
> fix(Select): initial value is not displayed when the component load

- packages/beeq/src/components/select/bq-select.tsx
Stop `bqClose` event from `bq-select` to propagate to parent. This prevents issues when the parent is emitting same event eg _Drawer_.
Fixes #1032
https://github.com/Endava/BEEQ/assets/109202804/cda58bcc-4245-4485-a7d3-8debcc42f1d7
> fix(Select): prevent bqClose to propagate further

- packages/beeq/src/components/select/__tests__/bq-select.e2e.ts
- packages/beeq/src/components/select/bq-select.tsx
This PR fixes the issue when for bq-select changing value externally does not update display value.
Fixes #1033
https://github.com/Endava/BEEQ/assets/109202804/f88c37d1-eb81-48fb-b16d-57851b962efb
> fix(select): re-render tags when value change externally

- packages/beeq/src/components/icon/__tests__/bq-icon.e2e.ts
- packages/beeq/src/components/icon/bq-icon.tsx
- packages/beeq/src/components/icon/helper/request.ts
- packages/beeq/stencil.config.ts
Removes the usage of Env. This functionality is covered by `setBasePath` exported from `shared/utils/assetsPath.ts`
Fixes #1044
> refactor(Icon): remove usage of `Env` from @stencil/core

- packages/beeq/src/components/button/scss/bq-button.scss
Change hover background color for button text and link based on Figma design here: https://www.figma.com/design/2VS47PTSkQWJkr7H6DpAdR/BEEQ-Design-System-(v1.0)?node-id=4840-33569&m=dev
> refactor(Button): change background color on hover for button link and text

- .circleci/config.yml
- packages/beeq-angular/package.json
- packages/beeq-react/package.json
- packages/beeq-vue/package.json
- packages/beeq-vue/src/plugin.ts
BEEQ integration with Vue.js is broken, because the latest Stencil version [no longer copies polyfills to the dist OT unless building es5](https://github.com/ionic-team/stencil/pull/5725), this PR aims to fix that.
N/A
> fix(Beeq Vue): remove `applyPolyfills()` function

- packages/beeq/src/components/select/scss/bq-select.scss
- project.json
This PR removes some useless CSS rules from the Select component label.
Fixes #1056
> refactor(Select): remove useless CSS rules

- packages/beeq/src/components/drawer/_storybook/bq-drawer.stories.tsx
- packages/beeq/src/components/drawer/bq-drawer.tsx
Adds possibility to override footer divider. If override is not provided will use the default figma design.
> feat(Drawer): add support for custom footer divider

- packages/beeq/src/tools/angular-value-accessor-config.ts
- packages/beeq/src/tools/vue-model-config.ts
Since the `bq-date-picker` is a form component,  we need to add it to the value accessor (Angular) and model config (Vue), but we missed that when the feature was implemented on #1029.
N/A
> fix(Date picker): missing value accessor and model config

- packages/beeq-tailwindcss/src/index.ts
- packages/beeq-tailwindcss/src/theme/default/root.ts
- packages/beeq/src/components/accordion/scss/bq-accordion.variables.scss
- packages/beeq/src/components/alert/scss/bq-alert.variables.scss
- packages/beeq/src/components/avatar/scss/bq-avatar.variables.scss
- packages/beeq/src/components/badge/scss/bq-badge.variables.scss
- packages/beeq/src/components/breadcrumb-item/scss/bq-breadcrumb-item.variables.scss
- packages/beeq/src/components/button/scss/bq-button.scss
- packages/beeq/src/components/button/scss/bq-button.variables.scss
- packages/beeq/src/components/card/scss/bq-card.variables.scss
- packages/beeq/src/components/checkbox/scss/bq-checkbox.variables.scss
- packages/beeq/src/components/date-picker/scss/bq-date-picker.variables.scss
- packages/beeq/src/components/drawer/_storybook/bq-drawer.stories.tsx
- packages/beeq/src/components/dropdown/_storybook/bq-dropdown.stories.tsx
- packages/beeq/src/components/icon/_storybook/bq-icon.stories.tsx
- packages/beeq/src/components/input/scss/bq-input.scss
- packages/beeq/src/components/input/scss/bq-input.variables.scss
- packages/beeq/src/components/option/scss/bq-option.variables.scss
- packages/beeq/src/components/radio/scss/bq-radio.variables.scss
- packages/beeq/src/components/select/scss/bq-select.variables.scss
- packages/beeq/src/components/side-menu/scss/bq-side-menu.scss
- packages/beeq/src/components/slider/bq-slider.tsx
- packages/beeq/src/components/slider/scss/bq-slider.scss
- packages/beeq/src/components/tab-group/scss/bq-tab-group.scss
- packages/beeq/src/components/tag/scss/bq-tag.variables.scss
- packages/beeq/src/components/textarea/scss/bq-textarea.variables.scss
The purpose of this PR is to enhance the consistency of our project's design elements, we need to introduce a standardized stroke size across the repository.
> feat(Tokens): add `--bq-stroke-*` token values for border width

- packages/beeq/src/components/slider/bq-slider.tsx
This PR fixes the issue on the Slider range, where the thumbs get stuck if the values (min/max) are both the maximum value or the minimum value allowed. As a workaround, we change the zIndex of the min or the max input value used under the hood.
Fixes #1073 
https://github.com/Endava/BEEQ/assets/328492/aac856d4-470b-438e-b3de-2ae46830c3ed
> fix(Slider): range thumbs being stuck when min/max values overlap

- packages/beeq/src/components/slider/bq-slider.tsx
- packages/beeq/src/shared/utils/__tests__/clamp.spec.ts
- packages/beeq/src/shared/utils/clamp.ts
- packages/beeq/src/shared/utils/index.ts
Fixes slider not updating when lower value is equal to upper value.
<table>
<thead>
<th>Before</th>
<th>After</th>
</thead>
<tbody>
<tr>
<td>
https://github.com/Endava/BEEQ/assets/109202804/4264d231-ba14-48e1-8147-c6564e07672c
</td>
<td>
https://github.com/Endava/BEEQ/assets/109202804/4f25b229-9d59-45c0-9d42-56ef3f354a3a
</td>
</tr>
</tbody>
</table>
> fix(Slider): lower value not updated when is equal to upper value

- packages/beeq/src/components/input/scss/bq-input.variables.scss
This PR fixes a regression bug on the Input component where the start/end paddings are missing due to a typo in the CSS custom properties defined.
N/A
> fix(Input): typo in CSS variables for padding start/end

- tools/src/generators/plop/scss-variables.hbs
The purpose of this PR is to update our generator for SCSS variables to be consistent with the changes in this PR: https://github.com/Endava/BEEQ/pull/1064
> chore(Generator): update theme spacing syntax in generator SCSS variables

- packages/beeq/src/components.d.ts
- packages/beeq/src/components/drawer/_storybook/bq-drawer.stories.tsx
- packages/beeq/src/components/drawer/bq-drawer.tsx
- packages/beeq/src/components/drawer/bq-drawer.types.ts
- packages/beeq/src/components/drawer/readme.md
We have moved from physical CSS properties to logical properties and to align with that we are deprecating the `placement` property in favor of the position prop with `start` | `end` values.
> With `placement` we were using `right` and `left` values which are no longer applicable in the context of using CSS logical properties.
> feat(Drawer): deprecate `placement` and add `position` property

- packages/beeq/src/components/input/_storybook/bq-input.stories.tsx
- packages/beeq/src/components/input/scss/bq-input.scss
> refactor(Input): use CSS logical properties instead of physical values

- packages/beeq/src/components/select/_storybook/bq-select.stories.tsx
- packages/beeq/src/components/select/bq-select.tsx
- packages/beeq/src/components/select/scss/bq-select.scss
Adds support for custom tag display when bq-select is multiple
> feat(Select): add support for custom tag display on multiple variant

- packages/beeq/src/components/divider/readme.md
- packages/beeq/src/components/page-title/__tests__/bq-page-title.e2e.ts
- packages/beeq/src/components/page-title/_storybook/bq-page-title.stories.tsx
- packages/beeq/src/components/page-title/bq-page-title.tsx
- packages/beeq/src/components/page-title/readme.md
- packages/beeq/src/components/page-title/scss/bq-page-title.scss
- packages/beeq/src/components/page-title/scss/bq-page-title.variables.scss
> refactor(Page Title): use CSS logical properties instead of physical values

- packages/beeq/src/components.d.ts
- packages/beeq/src/components/accordion-group/_storybook/bq-accordion-group.stories.tsx
- packages/beeq/src/components/accordion-group/bq-accordion-group.tsx
- packages/beeq/src/components/accordion-group/readme.md
- packages/beeq/src/components/accordion-group/scss/bq-accordion-group.scss
- packages/beeq/src/components/accordion/_storybook/bq-accordion.stories.tsx
- packages/beeq/src/components/accordion/bq-accordion.tsx
- packages/beeq/src/components/accordion/helper/index.ts
- packages/beeq/src/components/accordion/readme.md
- packages/beeq/src/components/accordion/scss/bq-accordion.scss
This PR aims to modernize the CSS by incorporating logical properties for improved adaptability and support for RTL content direction and vertical layout.
We have implemented CSS [animation for the summary HTML element](https://codepen.io/ZoranJambor/pen/jOorzPv?editors=1100) using block-size and [calc-size](https://github.com/WebKit/standards-positions/issues/348) (still in draft). If calc-size is supported:
the open/close animation will be handled via CSS instead of JavaScript. This enhances considerably the way the animation behaves on a vertical layout.
If calc-size() is not yet supported by the browser (feature flag is not enabled) animations will be handled via JavaScript, and, if there's a need for a vertical layout, we have added the possibility to disable all animation so the …
> refactor(Accordion): use CSS logical properties instead of physical values

- packages/beeq/src/components/drawer/_storybook/bq-drawer.stories.tsx
- packages/beeq/src/components/drawer/bq-drawer.tsx
This PR aims to solve an existing issue with the open/close animation behavior of the Drawer when the content direction switches from RTL to LTR, the animations are not working as expected since it's using `translate` which makes the drawer animates from/to the opposite side.
https://github.com/user-attachments/assets/9093d4c6-2cac-4382-8f5b-2cc27bd1e751
The fix removed the use of translation and relies on the inset-inline-start/end property, making it possible that animations work as expected regardless of the `direction="rtl | ltr"` set.
https://github.com/user-attachments/assets/d8a4a5e8-6e1a-4c9c-8deb-e2b15e2a3843
N/A
> fix(Drawer): open/close animation to be in sync with the content direction

- packages/beeq/src/components/icon/_storybook/bq-icon.stories.tsx
- packages/beeq/src/components/icon/scss/bq-icon.scss
- packages/beeq/src/global/styles/_components.scss
This PR adds the possibility to automatically flip the SVG icons horizontally when `dir="rtl"`. We have added a global custom property `--bq-icon--direction` that can be also used by consumers when a BqIcon needs to be flipped.
https://github.com/user-attachments/assets/987bb652-2bc0-470b-81c6-d3ec07bb912e
> feat(Icon): add `--bq-icon--direction` and flip SVG automatically for `dir="rtl"`

- packages/beeq/src/components/date-picker/_storybook/bq-date-picker.stories.tsx
- packages/beeq/src/components/date-picker/bq-date-picker.tsx
- packages/beeq/src/components/date-picker/scss/bq-date-picker.scss
> refactor(Date Picker): use CSS logical properties instead of physical values

- packages/beeq/src/components.d.ts
- packages/beeq/src/components/step-item/bq-step-item.tsx
- packages/beeq/src/components/step-item/readme.md
- packages/beeq/src/components/step-item/scss/bq-step-item.scss
- packages/beeq/src/components/steps/bq-steps.tsx
This PR refactors the CSS of BqStep and BqStepItem with CSS logical properties, to provide better support for RTL content layout.
https://github.com/user-attachments/assets/a141eb3d-7ea6-4360-99be-c2b066ef68a2
> refactor(Steps): use CSS logical properties instead of physical values

- packages/beeq/src/components/divider/__tests__/bq-divider.e2e.ts
- packages/beeq/src/components/divider/_storybook/bq-divider.stories.tsx
- packages/beeq/src/components/divider/bq-divider.tsx
- packages/beeq/src/components/divider/readme.md
- packages/beeq/src/components/divider/scss/bq-divider.scss
- packages/beeq/src/components/divider/scss/bq-divider.variables.scss
- packages/beeq/src/components/drawer/bq-drawer.tsx
- packages/beeq/src/components/steps/_storybook/bq-steps.stories.tsx
- packages/beeq/src/components/steps/bq-steps.tsx
- packages/beeq/src/components/steps/readme.md
This PR fixes the default values of the BqDivider as per Figma Design. 
- Text alignment will be set to the edge of the component when the value is not `middle`, meaning that the `stroke-basis` will default to `0`.
-  The `stroke-thickness` to be 1px.
- The `stroke-color` to be `stroke-primary`.
Dependant components like the Drawer and the Steps that use the divider under the hook have been updated accordingly.
https://github.com/user-attachments/assets/4287f66a-d44d-4579-8661-88939800a473
> fix(Divider): default values to be in sync with Figma design

- .husky/branch-name.sh
- package-lock.json
- packages/beeq-angular/package.json
- packages/beeq-react/package.json
- packages/beeq-vue/package.json
- packages/beeq/.eslintrc.json
- packages/beeq/package.json
This PR solves the issue where `@stencil/core` is missing as a dependency when using any framework output target within BEEQ.
It seems that `@stencil/core` should be added as a dependency of the core component library (`@beeq/core`) when using any framework output target.
Details: https://discord.com/channels/520266681499779082/1222546631816118305
N/A
> fix(deps): missing `@stencil/core` dependency for framework targets

- packages/beeq-tailwindcss/src/plugins/logical-properties.ts
- packages/beeq/src/components/checkbox/bq-checkbox.tsx
- packages/beeq/src/components/dropdown/_storybook/bq-dropdown.stories.tsx
- packages/beeq/src/components/icon/_storybook/bq-icon.stories.tsx
- packages/beeq/src/components/status/bq-status.tsx
- packages/beeq/src/components/steps/bq-steps.tsx
Adds support for negative values for logical properties inset/margin.
> chore(tailwind): support for negative values for logical properties inset/margin

- .vscode/settings.json
- packages/beeq/src/components.d.ts
- packages/beeq/src/components/drawer/bq-drawer.tsx
- packages/beeq/src/components/drawer/bq-drawer.types.ts
- packages/beeq/src/components/icon/_storybook/bq-icon.stories.tsx
- packages/beeq/src/components/icon/bq-icon.tsx
- packages/beeq/src/components/icon/bq-icon.types.ts
- packages/beeq/src/components/icon/readme.md
- packages/beeq/src/components/icon/scss/bq-icon.scss
- packages/beeq/src/shared/utils/assetsPath.ts
This PR deprecates the `weight` property on the Icon component. This property was added when we had the SVG assets split in a different folder by weight: `thin`, `light`, `regular`, `fill`, `bold`, and `duotone`, but the SVG assets have been merged into a single folder and the weight can now be set within the icon name itself, if before we could have:
```html
<bq-icon name="bell" size="24" weight="bold"></bq-icon>
```
now we can archive the same by doing the following:
```html
<bq-icon name="bell-bold" size="24"></bq-icon>
```
Also, we have improved the `setBasePath()` and now users can specify even remote URLs in order to use a different icon library
N/A
We have also added VSCode Anchors to highlight what needs to be removed in the future.
> feat(Icon): deprecate `weight` property

- packages/beeq/src/components.d.ts
- packages/beeq/src/components/tab-group/_storybook/bq-tab-group.stories.tsx
- packages/beeq/src/components/tab-group/bq-tab-group.tsx
- packages/beeq/src/components/tab-group/readme.md
- packages/beeq/src/components/tab-group/scss/bq-tab-group.scss
- packages/beeq/src/components/tab/_storybook/bq-tab.stories.tsx
- packages/beeq/src/components/tab/bq-tab.tsx
- packages/beeq/src/components/tab/bq-tab.types.ts
- packages/beeq/src/components/tab/readme.md
- packages/beeq/src/components/tab/scss/bq-tab.scss
https://github.com/user-attachments/assets/d11a835c-864e-419d-862f-4d58c962ef53
Fixes #1092
> feat(Tab): add orientation support

- packages/beeq/src/components/input/_storybook/bq-input.stories.tsx
- packages/beeq/src/components/input/bq-input.tsx
* https://stenciljs.com/docs/forms#using-form-associated-custom-elements
* https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/attachInternals
Currently, to attach the `<bq-input>` component to a form users need to do so manually. With this PR, users only need to be aware of setting the component name attribute/property to be linked to the form.
https://github.com/user-attachments/assets/07c33e4b-b77f-4b7d-a1fd-6774827241db
> feat(Input): enable support for form-associated

- packages/beeq/src/components/select/_storybook/bq-select.stories.tsx
- packages/beeq/src/components/select/bq-select.tsx
* https://stenciljs.com/docs/forms#using-form-associated-custom-elements
* https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/attachInternals
Currently, to attach the `<bq-select>` component to a form users need to do so manually. With this PR, users only need to be aware of setting the component name attribute/property to be linked to the form.
https://github.com/user-attachments/assets/03ff30d8-20e5-4e88-b4a8-dbc59998525b
> feat(Select): enable support for form-associated 

- .github/renovate.json5
- packages/beeq/src/components.d.ts
- packages/beeq/src/components/checkbox/_storybook/bq-checkbox.stories.tsx
- packages/beeq/src/components/checkbox/bq-checkbox.tsx
- packages/beeq/src/components/checkbox/readme.md
https://stenciljs.com/docs/forms#using-form-associated-custom-elements
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/attachInternals
Currently, adding a `<bq-checkbox>` element to a form does not result in its participation in the form submission, even when a `name` and `formId` are provided. With this pull request, users need only to set the component's name attribute/property to link it to the form. Additionally, it enables validation of the element when 'required' is present, thus preventing form submission if the BqCheckbox is not selected or checked.
https://github.com/user-attachments/assets/4ff5df81-ca8b-41c6-a4b3-0c9d119d0dbf
> feat(Checkbox): enable support for form-associated

- packages/beeq/src/components/select/bq-select.tsx
This pull request resolves an issue with the Select component not displaying the selected value when the initial value is set directly. For example, when having something like the following:
```jsx
<BqSelect
name="gender"
placeholder="Select from the list"
value="Rather not say"
>
<BqOption value="male">Male</BqOption>
<BqOption value="female">Female</BqOption>
<BqOption value="rather not say">Rather not say</BqOption>
</BqSelect>
```
The component renders with an empty display value, even though the 'Male' option is selected.
> fix(Select): display value is not shown when initial value is set

- packages/beeq/src/shared/utils/assetsPath.ts
Some of the latest changes with the asset paths require projects to set the base path regardless of whether they use the default location. With this PR, if the base path has not been set and there's no BEEQ script added to the HTML, we will set the assets path to the default location: `/svg` and avoid projects doing so on their end. This time we are also setting the value in the window object to keep persistence since using a global variable is flaky when protect sets the base path but it is not taken into account when BqIcon calls `getBasePath()`.
> fix(Assets): set SVG base path in the window object to keep persistence

- packages/beeq/src/components.d.ts
- packages/beeq/src/components/alert/_storybook/bq-alert.stories.tsx
- packages/beeq/src/components/alert/bq-alert.tsx
- packages/beeq/src/components/alert/readme.md
This pull request enables users to specify an alternative close button for the Alert component through a slot, particularly when using a custom icon library.
> fix(Alert): make close icon customizable via slot

- packages/beeq/src/components/notification/bq-notification.tsx
- packages/beeq/src/components/notification/readme.md
This PR shifts the creation of the notification portal container from outside the component into the `connectedCallback()` lifecycle method. This change is necessary to support SSR #1216 and to prevent errors when calling the window or document object from the server, where they are not available.
N/A
> refactor(Notification): set notification portal from the components lifecycle: `connectedCallback()`

- packages/beeq/src/components/toast/__tests__/bq-toast.e2e.ts
- packages/beeq/src/components/toast/_storybook/bq-toast.stories.tsx
- packages/beeq/src/components/toast/bq-toast.tsx
- packages/beeq/src/components/toast/readme.md
This PR shifts the creation of the toast portal container from outside the component into the connectedCallback() lifecycle method. This change is necessary to support SSR https://github.com/Endava/BEEQ/pull/1216 and prevent errors when calling the window or document object from the server, where they are unavailable.
> refactor(Toast): set toast portal from the components lifecycle: `connectedCallback()`

- packages/beeq/src/components/icon/_storybook/bq-icon.stories.tsx
- packages/beeq/src/shared/utils/assetsPath.ts
This pull request ensures that `bqSVGBasePath` is assigned to the global window object only when both the window and document (_including a query to the document object_) are accessible on the client side. This adjustment is crucial for enabling SSR as seen in https://github.com/Endava/BEEQ/pull/1216, and it helps avoid errors that occur when the window or document objects are referenced server-side, where they do not exist.
> refactor(Assets Path): set `bqSVGBasePath` when window and document objects are available

- packages/beeq-angular/README.md
- packages/beeq-react/README.md
- packages/beeq-vue/README.md
- packages/beeq/README.md
This PR updates the README documentation of each package.
N/A
> docs: update README documentation of each package

- packages/beeq-angular/tsconfig.lib.prod.json
- packages/beeq/stencil.config.ts
This option allows Angular Language Service to type-check and show jsdocs when using the components in html-templates.
N/A
> feat(BEEQ Angular): enable `inlineProperties` config

- packages/beeq/src/components.d.ts
- packages/beeq/src/components/radio-group/_storybook/bq-radio-group.stories.tsx
- packages/beeq/src/components/radio-group/bq-radio-group.tsx
- packages/beeq/src/components/radio-group/readme.md
- packages/beeq/src/components/radio/bq-radio.tsx
- packages/beeq/src/components/radio/readme.md
- packages/beeq/src/components/radio/scss/bq-radio.scss
https://stenciljs.com/docs/forms#using-form-associated-custom-elements
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/attachInternals
To attach the <bq-radio> component to a form, users need to do so manually. With this PR, users only need to be aware of setting the component name attribute/property to be linked to the form.
N/A
https://github.com/user-attachments/assets/ca7a4133-2414-462d-92ec-30717db2e6dc
> feat(Radio): enable support for form-associated

- packages/beeq/src/components/date-picker/_storybook/bq-date-picker.stories.tsx
- packages/beeq/src/components/date-picker/bq-date-picker.tsx
- packages/beeq/src/components/input/bq-input.tsx
https://stenciljs.com/docs/forms#using-form-associated-custom-elements
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/attachInternals
To attach the <bq-date-picker> component to a form, users need to do so manually. With this PR, users only need to be aware of setting the component name attribute/property to be linked to the form.
Fixes N/A
https://github.com/user-attachments/assets/82059f12-b2b2-4d1a-abfb-03c2d8bcb026
> feat(Date picker): enable support for form-associated

- packages/beeq/src/components/accordion/bq-accordion.tsx
- packages/beeq/src/components/accordion/scss/bq-accordion.scss
With this PR, we replace the use of the calc-size() feature, which is only supported if a feature flag is enabled in the browser, with the interpolate-size property to animate the accordion's opening and closing. Chrome browsers already support this without the need to enable something extra in the client's browser.
More details can be found here: [https://chrome.dev/css-wrapped-2024/#animate-to-height-auto](https://chrome.dev/css-wrapped-2024/#animate-to-height-auto)
N/A
> refactor(Accordion): replace `calc-size()` animation with `interpolate-size`

- package-lock.json
- package.json
- packages/beeq/cem.config.mjs
- packages/beeq/eslint.config.js
- patches/@nxext+stencil+20.0.6.patch
The `cem-plugin-custom-jsdoc-tags` package has been marked as `deprecated` by the author.
N/A
> chore(deps): replace `cem-plugin-custom-jsdoc-tags` dependency with `@wc-toolkit/jsdoc-tags`

- packages/beeq/src/components/select/bq-select.tsx
Fixed and issue where clelaring the select input with Backspace leads into having `undefined` string as input value and cannot be removed.
Fixes #1461
> fix(Select): change value clearing logic to use empty string instead undefined

- .github/CODEOWNERS
- packages/beeq/src/components.d.ts
- packages/beeq/src/components/select/_storybook/bq-select.stories.tsx
- packages/beeq/src/components/select/bq-select.tsx
- packages/beeq/src/components/select/readme.md
This PR adds a new `bqInput` event emitted by the `BqSelect` component when filtering (typing in the input used under the hood). This will allow consumers to customize the behavior of the Select by having the ability to `preventDefault()` the event and implement their custom logic. E.g., show loading state while fetching the options upon query filter, show `No results`, etc.
> feat(Select): add bqInput event for real-time input value changes when filtering

- packages/beeq/src/components.d.ts
- packages/beeq/src/components/select/_storybook/bq-select.stories.tsx
- packages/beeq/src/components/select/bq-select.tsx
- packages/beeq/src/components/select/readme.md
- packages/beeq/src/shared/utils/__tests__/stringToArray.spec.ts
- packages/beeq/src/shared/utils/index.ts
- packages/beeq/src/shared/utils/stringToArray.ts
This PR adds a new reset memthod to the BqSelect component, allowing consumers to reset the select value to a previous value without triggering BqChange event.
N/A
With the following changes, consumers will be able to do something like:
```ts
const bqSelectRef = useRef<HTMLBqSelectElement>(null);
const handleSelectChange = async (
event: BqSelectCustomEvent<{ value: TSelectValue | number; item: HTMLBqOptionElement }>,
) => {
console.log('Selected value', event.detail.value);
//... other logic here
if (bqSelectRef.current) {
await bqSelectRef.current.reset(String(3)); 
}
};
return (
<BqSelect onBqSelect={handleSelectChange} ref={bqSelectRef}>
<BqOption value="1">1</BqOption>
<BqOption value="2">2</BqOption>
<BqOption value="3">3</BqOption>
</BqSelect>
)
```
> feat(Select): add reset method to restore to a previous value

- packages/beeq-tailwindcss/src/theme/default/dark.ts
- packages/beeq-tailwindcss/src/theme/default/light.ts
- packages/beeq-tailwindcss/src/theme/endava/dark.ts
- packages/beeq-tailwindcss/src/theme/endava/light.ts
- packages/beeq/src/components.d.ts
- packages/beeq/src/components/step-item/__tests__/bq-step-item.e2e.ts
- packages/beeq/src/components/step-item/bq-step-item.tsx
- packages/beeq/src/components/step-item/readme.md
- packages/beeq/src/components/step-item/scss/bq-step-item.scss
- packages/beeq/src/components/steps/__tests__/bq-steps.e2e.ts
- packages/beeq/src/components/steps/_storybook/bq-steps.stories.tsx
- packages/beeq/src/components/steps/bq-steps.tsx
- packages/beeq/src/components/steps/readme.md
- packages/beeq/src/components/steps/scss/bq-steps.scss
This PR changes the component's internal wrapper from `div` to `button` enabling interaction behaviour and improving accessibility. The component now emits the `bqClick`, `bqFocus`, and `bqBlur` events as expected, as they were missed in the initial implementation.
When clicking a new step item, it will become the current active step. The behaviour can be changed by using `event.PreventDefault()` on the `bqClick` handler of the step item.
Fixes #1498 
https://github.com/user-attachments/assets/19227856-ee78-44d4-8424-6b34a2443da2
> fix(Step Item): improve accessibility and interaction behaviour

- packages/beeq/src/components.d.ts
- packages/beeq/src/components/tooltip/__tests__/bq-tooltip.e2e.ts
- packages/beeq/src/components/tooltip/bq-tooltip.tsx
- packages/beeq/src/components/tooltip/readme.md
This PR adds event emissions for tooltip interactions and enhances end-to-end tests. This allows developers to respond to click, focus, and hover events on the tooltip trigger.
**Changes**
- Added `bqClick`, `bqFocusIn`, `bqFocusOut`, `bqHoverIn`, and `bqHoverOut` events to `bq-tooltip` component.
- Modified bq-tooltip.tsx to emit these events during corresponding trigger interactions.
- Enhanced bq-tooltip.e2e.ts to include tests for event prevention and interaction behaviors.
**Impact**
- Developers can now listen for and react to click, focus, and hover events on the tooltip trigger, providing greater control and customization options.
- The new events allow for more complex tooltip interactions and integration with other components.
- The end-to-end tests ensure the events are …
> feat(Tooltip): enable prevention of behaviour for click, focus, and hover events
